<a href="https://colab.research.google.com/github/Ragnar1999/Deep-learning/blob/master/tensorflow2ttl02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Build your first ANN***

activation function
-sigmoid
-relu/leaky relu
-softmax

In [0]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Flatten,Dense

In [6]:
print(tf.__version__)

2.2.0-rc3


In [0]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
dataset=pd.read_csv('./sample_data/Churn_Modelling.csv')

In [10]:
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [0]:
X=dataset.drop(labels=["CustomerId","Surname","RowNumber","Exited"],axis=1)
y=dataset["Exited"]
     

In [13]:
X.head()

CreditScore Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female  ...          1               1        101348.88
1          608     Spain  Female  ...          0               1        112542.58
2          502    France  Female  ...          1               0        113931.57
3          699    France  Female  ...          0               0         93826.63
4          850     Spain  Female  ...          1               1         79084.10

[5 rows x 10 columns]

In [14]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [0]:
from sklearn.preprocessing import LabelEncoder
label1=LabelEncoder(
)
X["Geography"]=label1.fit_transform(X["Geography"])

In [17]:
X.head(10)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0  Female  ...          1               1        101348.88
1          608          2  Female  ...          0               1        112542.58
2          502          0  Female  ...          1               0        113931.57
3          699          0  Female  ...          0               0         93826.63
4          850          2  Female  ...          1               1         79084.10
5          645          2    Male  ...          1               0        149756.71
6          822          0    Male  ...          1               1         10062.80
7          376          1  Female  ...          1               0        119346.88
8          501          0    Male  ...          0               1         74940.50
9          684          0    Male  ...          1               1         71725.73

[10 rows x 10 columns]

In [0]:
label=LabelEncoder()
X["Gender"]=label.fit_transform(X["Gender"])

In [20]:
X.head(10)

CreditScore  Geography  Gender  ...  HasCrCard  IsActiveMember  EstimatedSalary
0          619          0       0  ...          1               1        101348.88
1          608          2       0  ...          0               1        112542.58
2          502          0       0  ...          1               0        113931.57
3          699          0       0  ...          0               0         93826.63
4          850          2       0  ...          1               1         79084.10
5          645          2       1  ...          1               0        149756.71
6          822          0       1  ...          1               1         10062.80
7          376          1       0  ...          1               0        119346.88
8          501          0       1  ...          0               1         74940.50
9          684          0       1  ...          1               1         71725.73

[10 rows x 10 columns]

In [22]:
 X=pd.get_dummies(X,drop_first=True, columns=["Geography"])
 X.head()

CreditScore  Gender  Age  ...  EstimatedSalary  Geography_1  Geography_2
0          619       0   42  ...        101348.88            0            0
1          608       0   41  ...        112542.58            0            1
2          502       0   42  ...        113931.57            0            0
3          699       0   39  ...         93826.63            0            0
4          850       0   43  ...         79084.10            0            1

[5 rows x 11 columns]

Feature Standardization


In [0]:
from sklearn.preprocessing import StandardScaler

In [0]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,stratify=y)
scaler=StandardScaler(
)
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [25]:
X_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

Build ANN


In [0]:
model=Sequential()
model.add(Dense(X.shape[1],activation="relu",input_dim=X.shape[1]))
model.add(Dense(128,activation="relu"))
model.add(Dense(1,activation="sigmoid"))

In [0]:
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [29]:
model.fit(X_train,y_train.to_numpy(),batch_size=10,epoch=10,verbose=1)

800/800 [==============================] - 1s 1ms/step - loss: 0.4538 - accuracy: 0.8064


In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 11)                132       
_________________________________________________________________
dense_1 (Dense)              (None, 128)               1536      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 129       
Total params: 1,797
Trainable params: 1,797
Non-trainable params: 0
_________________________________________________________________


In [0]:
y_pred=model.predict_classes(X_test)

In [33]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int32)

In [35]:
y_test


1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [36]:
model.evaluate(X_test,y_test.to_numpy() )

63/63 [==============================] - 0s 1ms/step - loss: 0.4254 - accuracy: 0.8270


[0.42540571093559265, 0.8270000219345093]

In [0]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [38]:
confusion_matrix(y_test,y_pred)

array([[1548,   45],
       [ 301,  106]])

In [39]:
accuracy_score(y_test,y_pred)

0.827